- hosts: nodes

  environment:
    PLACEHOLDER_VAR: "foobar"

  vars_files:
    - "../settings_field_node.yml"

  vars:
    security_ssh_port: "{{ ssh_port }}"

  roles:
    - geerlingguy.security

  tasks:
    - name: Install build dependencies
      apt: pkg=build-essential state=installed

    - name: Install htop
      apt: pkg=htop state=installed

    - name: Install openssh-server
      apt: pkg=openssh-server state=installed

    - name: Install git
      apt: pkg=git state=installed

    # If using the dual-NIC expresscard34 card with Realtek 8168
    # - name: Install dual-nic driver
    #   script: ./files/install_r8168_drivers.sh
    #   become: yes

    # - name: Copy in service to renew DHCP lease when expresscard NIC is inserted
    #   template: 
    #     src: "./files/enp12s0_watcher.service.j2"
    #     dest: "/etc/systemd/system/enp12s0_watcher.service"
    #     mode: "0644"
    #   register: enp12s0_service_file

    # - shell: "systemctl daemon-reload && systemctl enable enp12s0_watcher"
    #   when: enp12s0_service_file.changed

    - name: Install ansible
      apt: pkg=ansible state=installed

    - name: Install tmux
      apt: pkg=tmux state=installed

    - name: Install python-dev
      apt: pkg=python-dev state=installed

    - name: download pip installer script
      get_url: 
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "/opt/get-pip.py"
        mode: "0755"
      register: pip_script_downloaded
    - name: install pip
      command: "python /opt/get-pip.py"
      when: pip_script_downloaded|success

    - name: Create file copy destination on remote
      file: path=/opt/field-node state=directory mode=0755

    - name: Copy python dependency file 
      copy: 
        src: "./files/requirements.txt"
        dest: "/opt/field-node/python-requirements.txt"
        mode: "0744"

    - name: Install python dependencies
      pip: 
        requirements: "/opt/field-node/python-requirements.txt"

    # - name: Ensure .ssh directory exists.
    #   file: 
    #     dest: "/home/ubuntu/.ssh"
    #     mode: 0700 
    #     owner: ubuntu
    #     state: directory

    # - name: Install deployment ssh key
    #   copy: 
    #     content: "{{ deploy_ssh_private_key }}" 
    #     dest: "/home/ubuntu/.ssh/id_rsa"
    #     mode: 0600
    #     owner: ubuntu

    #- name: setup cron job to call ansible-pull every hour
    #  cron: 
    #    name: "update route53"
    #    minute: "5"
    #    user: ubuntu
    #    job: "ansible-pull -U {{deploy_repo_url}} -i ./production ./field-node/base_playbook.yml"
