- hosts: nodes
  vars_files:
    - "../settings_field_node.yml"
  vars:
    samba_shares: []
    samba_service_names: ['smbd','nmbd']

    # used to fake available storage on the samba share
    # since the MiSeq wants 100GB even though it needs much less (~5GB/run)
    dfree_script: "/opt/field-node/faked_dfree.sh"

    seqdata_archival_path: "/media/seqdata"
    move_data_older_than_days: "5"

  vars_prompt:
    - name: "samba_username"
      prompt: "Enter samba username"
      private: no

    - name: "samba_user_password"
      prompt: "Enter samba user password"
      private: yes

  roles: 
    - debops.samba

  tasks:
    - name: add samba user for shared data directory
      user: 
        name: "{{ samba_username }}"
        comment: "samba user for shared data directory" 
        shell: /usr/sbin/nologin

    - name: set samba user password
      shell: "(echo {{ samba_user_password }}; echo {{ samba_user_password }}) | smbpasswd -s -a {{ samba_username }}"

    - name: restart samba services
      service: 
        name: "{{ item }}" 
        state: "restarted"
      with_items: "{{ samba_service_names }}"

    - name: Copy in data moving script (for old data)
      template: 
        src: "./files/move_old_subdirs.sh" 
        dest: "/opt/field-node/move_old_subdirs.sh"
        mode: "0755"

    - name: Create samba folder for user
      file: 
        path: "{{ samba_homes_path }}/{{samba_username}}" 
        state: directory
        mode: 0775

    - name: Copy in samba share readme
      template: 
        src: "./files/PUT_MISEQ_OUTPUT_HERE.txt" 
        dest: "{{ samba_homes_path }}/{{samba_username}}/PUT_MISEQ_OUTPUT_HERE.txt"
        mode: "0755"

    - name: get list of users
      shell: "cut -d: -f1 /etc/passwd"
      register: user_list_cmd

    - name: add all existing users on system to same group as samba user
      user: 
        name: "{{ item }}"
        groups: "{{ samba_username }}"
        append: "yes"
      become: yes
      with_items:
        - "{{ user_list_cmd.stdout_lines }}"

    - name: Copy in data moving script (for old data)
      template: 
        src: "./files/faked_dfree.sh" 
        dest: "/opt/field-node/faked_dfree.sh"
        mode: "0755"

    # this script will be called hourly, but its action should be performed as a post-upload hook
    # with the cron job as a fallback
    - cron: 
        name: "move old data" 
        special_time: "hourly" 
        state: "present"
        job: "/opt/field-node/move_old_subdirs.sh {{ samba_homes_path }}/{{samba_username}} {{ seqdata_archival_path }} {{ move_data_older_than_days }}"

    - debug:
        msg: "User samba home created: {{ samba_homes_path }}/{{samba_username}}"