name: "remote config ansible test"

on:
  push:
  pull_request:
    branches:
      - master
  release:
    types:
      - created
  schedule:
    - cron: '0 18 * * 1' # weekly at 18:00 on Mondays

env:
  TEST_ANSIBLE_HOSTNAME: localhost
  TEST_ANSIBLE_CONNECTION: local

jobs:
  check_playbook_syntax:
    runs-on: ubuntu-22.04
    env:
      GITHUB_ACTIONS_PYTHON_VERSION: 3.8
    steps:
      - name: update apt repo info
        run: sudo apt-get update -qq
      - name: install apt packages
        run: sudo apt-get install -y python3-apt python3-pycurl
      - name: install pip packages
        run: |
          pip install --upgrade pip
          pip install ansible netaddr
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install ansible and deps
        run: |
          pip install --upgrade pip
          pip install ansible netaddr
      - name: prepare settings template files
        run: |
          cp settings_field_node.yml.template settings_field_node.yml
          cp settings_manager.yml.template settings_manager.yml
      - name: check syntax of ansible playbooks
        run: |
          ansible-playbook --syntax-check -i test/inventory test/playbook.yml
          ansible-playbook --syntax-check -i test/inventory management-node/manager-base.yml
          ansible-playbook --syntax-check -i test/inventory management-node/manager-sensu.yml
          # ansible as of 2.0.0.2 has a bug where syntax checking fails if vars_prompt is used
          # once it has been resolved, node-full.yml or node-*.yml can be used
          ansible-playbook --syntax-check -i test/inventory field-node/node-full.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-tunnel.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-users.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-base.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-restart-autossh.yml
          #ansible-playbook --syntax-check -i test/inventory field-node/compile-and-install-python2.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-dx-uploader.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-geoip.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-mounts.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-power-policy.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-samba.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-sensu.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-tunnel.yml
          ansible-playbook --syntax-check -i test/inventory field-node/node-users.yml
          ansible-playbook --syntax-check -i test/inventory field-node/set-sources-list-to-old-release.yml